# Generated by Django 6.0.4 on 2026-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20)),
                ('asignatura', models.CharField(max_length=100)),
                ('nota1', models.FloatField()),
                ('nota2', models.FloatField()),
                ('nota3', models.FloatField()),
                ('promedio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
